name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install tools
        run: make tools
      - name: Run CUE validation
        run: make vet
      - name: Create Kind cluster
        run: kind create cluster --wait=5m
      - name: Install Flux
        run: make install
      - name: Verify installation
        run: flux check
