name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install tools
        run: make tools
      - name: Run CUE validation
        run: make vet
      - name: Create cluster without CNI
        run: kind create cluster --config ./test/cni/kind.yaml
      - name: Install Flux
        run: make install
      - name: Verify Flux installation
        run: flux check
      - name: Install Cilium with Flux
        run: kubectl apply -f ./test/cni/cilium.yaml
      - name: Verify Cilium installation
        run: kubectl -n kube-system wait helmrelease/cilium --for=condition=ready --timeout=5m
      - name: Verify CoreDNS availability
        run: kubectl -n kube-system rollout status deploy/coredns --timeout=5m
